// stlExporter.js
// Convert an indexed triangle mesh ({positions, indices}) into a binary STL.
// Binary STL layout:
//   80-byte header
//   uint32 triangle count
//   per triangle: 3x float32 normal, 3x (3x float32 vertex), uint16 attribute

export function meshToBinarySTL(mesh) {
  const { positions, indices } = mesh;
  const triCount = indices.length / 3;

  const bufferSize = 84 + triCount * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // Header (80 bytes) — leave a friendly label, harmless to slicers.
  const header = 'Generated by LampGenerator (parametric lamp shade)';
  for (let i = 0; i < 80; i++) {
    view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }

  view.setUint32(80, triCount, true);

  let offset = 84;
  const ax = new Array(3), bx = new Array(3), cx = new Array(3);

  for (let f = 0; f < triCount; f++) {
    const ia = indices[f * 3] * 3;
    const ib = indices[f * 3 + 1] * 3;
    const ic = indices[f * 3 + 2] * 3;

    ax[0] = positions[ia];     ax[1] = positions[ia + 1]; ax[2] = positions[ia + 2];
    bx[0] = positions[ib];     bx[1] = positions[ib + 1]; bx[2] = positions[ib + 2];
    cx[0] = positions[ic];     cx[1] = positions[ic + 1]; cx[2] = positions[ic + 2];

    // Face normal = (b-a) x (c-a), normalized.
    const ux = bx[0] - ax[0], uy = bx[1] - ax[1], uz = bx[2] - ax[2];
    const vx = cx[0] - ax[0], vy = cx[1] - ax[1], vz = cx[2] - ax[2];
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    const len = Math.hypot(nx, ny, nz) || 1;
    nx /= len; ny /= len; nz /= len;

    view.setFloat32(offset, nx, true); offset += 4;
    view.setFloat32(offset, ny, true); offset += 4;
    view.setFloat32(offset, nz, true); offset += 4;

    for (const vtx of [ax, bx, cx]) {
      view.setFloat32(offset, vtx[0], true); offset += 4;
      view.setFloat32(offset, vtx[1], true); offset += 4;
      view.setFloat32(offset, vtx[2], true); offset += 4;
    }

    view.setUint16(offset, 0, true); offset += 2; // attribute byte count
  }

  return new Blob([buffer], { type: 'model/stl' });
}

export function downloadSTL(mesh, filename = 'lamp.stl') {
  const blob = meshToBinarySTL(mesh);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
